/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Com
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    User user;
    String filename = null;
    public CreateJPanel(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCareer = new javax.swing.JLabel();
        jLabelDegree2 = new javax.swing.JLabel();
        jLabelDegree2SD = new javax.swing.JLabel();
        jLabelDegree2ED = new javax.swing.JLabel();
        jLabelLastname = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelStreet2 = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelMajor = new javax.swing.JLabel();
        jLabelDegree1 = new javax.swing.JLabel();
        jLabelDegree1SD = new javax.swing.JLabel();
        jLabelDegree1ED = new javax.swing.JLabel();
        jLabelFirstname = new javax.swing.JLabel();
        jLabelEducational = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelTele = new javax.swing.JLabel();
        jLabelStreet1 = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelResidential = new javax.swing.JLabel();
        jLabelPersonal = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelAffiliation = new javax.swing.JLabel();
        jTextFieldDOB = new javax.swing.JTextField();
        jTextFieldTele = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldStreet1 = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldStreet2 = new javax.swing.JTextField();
        jTextFieldCountry = new javax.swing.JTextField();
        jTextFieldAffiliation = new javax.swing.JTextField();
        jTextFieldDegree1 = new javax.swing.JTextField();
        jTextFieldDegree1SD = new javax.swing.JTextField();
        jTextFieldDegree1ED = new javax.swing.JTextField();
        jTextFieldCareer = new javax.swing.JTextField();
        jTextFieldMajor = new javax.swing.JTextField();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldDegree2 = new javax.swing.JTextField();
        jTextFieldDegree2SD = new javax.swing.JTextField();
        jTextFieldDegree2ED = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonUpload = new javax.swing.JButton();

        jLabelCareer.setText("Career");

        jLabelDegree2.setText("Degree 2 ");

        jLabelDegree2SD.setText("Degree 2 Start Date");

        jLabelDegree2ED.setText("Degree 2 End Date");

        jLabelLastname.setText("Last Name");

        jLabelAge.setText("Age");

        jLabelEmail.setText("Email");

        jLabelStreet2.setText("Street Line 2");

        jLabelCountry.setText("Country");

        jLabelMajor.setText("Major");

        jLabelDegree1.setText("Degree 1");

        jLabelDegree1SD.setText("Degree 1 Start Date");

        jLabelDegree1ED.setText("Degree 1 End Date");

        jLabelFirstname.setText("First Name");

        jLabelEducational.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEducational.setText("Educational Details :");

        jLabelDOB.setText("DOB");

        jLabelTele.setText("Telephone Number");

        jLabelStreet1.setText("Street Line 1");

        jLabelPhoto.setText("Profile Photo");

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Create User Profile");

        jLabelResidential.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelResidential.setText("Residential Details :");

        jLabelPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPersonal.setText("Personal Details :");

        jLabelCity.setText("City");

        jLabelAffiliation.setText("Affiliation");

        jTextFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOBActionPerformed(evt);
            }
        });

        jTextFieldLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastnameActionPerformed(evt);
            }
        });

        jTextFieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstnameActionPerformed(evt);
            }
        });

        jButtonSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonUpload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonUpload.setText("Upload Image");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDOB)
                    .addComponent(jLabelFirstname)
                    .addComponent(jLabelTele)
                    .addComponent(jLabelPersonal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelResidential)
                            .addComponent(jLabelStreet1)
                            .addComponent(jLabelEducational)
                            .addComponent(jLabelAffiliation)
                            .addComponent(jLabelDegree1)
                            .addComponent(jLabelDegree1SD)
                            .addComponent(jLabelPhoto))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelCareer)
                                .addComponent(jLabelDegree1ED)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(jLabelCity))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAffiliation)
                                    .addComponent(jTextFieldDegree1)
                                    .addComponent(jTextFieldDegree1SD)
                                    .addComponent(jTextFieldCareer)
                                    .addComponent(jTextFieldCity)
                                    .addComponent(jTextFieldStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelStreet2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelCountry, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelMajor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelDegree2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDegree2SD)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldTele, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLastname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDegree1ED, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabelDegree2ED)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldStreet2)
                                .addComponent(jTextFieldCountry)
                                .addComponent(jTextFieldMajor)
                                .addComponent(jTextFieldDegree2)
                                .addComponent(jTextFieldDegree2SD)
                                .addComponent(jTextFieldDegree2ED, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldLastname)
                                .addComponent(jTextFieldAge)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLastname)
                                    .addComponent(jTextFieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAge)
                                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFirstname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDOB))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTele))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPhoto)
                                    .addComponent(jButtonUpload))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStreet2)
                            .addComponent(jTextFieldStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCountry)
                            .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jTextFieldMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDegree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDegree2SD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDegree2ED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelResidential)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStreet1)
                            .addComponent(jTextFieldStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCity)
                            .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEducational)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAffiliation)
                            .addComponent(jTextFieldAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMajor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDegree1)
                            .addComponent(jTextFieldDegree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDegree2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDegree1SD)
                            .addComponent(jTextFieldDegree1SD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDegree2SD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDegree1ED)
                            .addComponent(jTextFieldDegree1ED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDegree2ED))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCareer)
                    .addComponent(jTextFieldCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOBActionPerformed

    private void jTextFieldLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastnameActionPerformed

    private void jTextFieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        user.setFirstname(jTextFieldFirstname.getText());
        user.setLastname(jTextFieldLastname.getText());
        user.setDob(jTextFieldDOB.getText());
        user.setAge(Integer.parseInt(jTextFieldAge.getText()));
        user.setTelephone(Long.parseLong(jTextFieldTele.getText()));
        user.setEmail(jTextFieldEmail.getText());
        user.setStreetline1(jTextFieldStreet1.getText());
        user.setStreetline2(jTextFieldStreet2.getText());
        user.setCity(jTextFieldCity.getText());
        user.setCountry(jTextFieldCountry.getText());
        user.setAffiliation(jTextFieldAffiliation.getText());
        user.setMajor(jTextFieldMajor.getText());
        user.setCareer(jTextFieldCareer.getText());
        user.setDegree1(jTextFieldDegree1.getText());
        user.setDegree1start(jTextFieldDegree1SD.getText());
        user.setDegree1end(jTextFieldDegree1ED.getText());
        user.setDegree2(jTextFieldDegree2.getText());
        user.setDegree2start(jTextFieldDegree2SD.getText());
        user.setDegree2end(jTextFieldDegree2ED.getText());
        
        JOptionPane.showMessageDialog(this, "Information is saved!!");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        user.setFilename(f.getAbsolutePath());
        JOptionPane.showMessageDialog(this, "Image Uploaded Successfully!!");
    }//GEN-LAST:event_jButtonUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JLabel jLabelAffiliation;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelCareer;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelDegree1;
    private javax.swing.JLabel jLabelDegree1ED;
    private javax.swing.JLabel jLabelDegree1SD;
    private javax.swing.JLabel jLabelDegree2;
    private javax.swing.JLabel jLabelDegree2ED;
    private javax.swing.JLabel jLabelDegree2SD;
    private javax.swing.JLabel jLabelEducational;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelLastname;
    private javax.swing.JLabel jLabelMajor;
    private javax.swing.JLabel jLabelPersonal;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelResidential;
    private javax.swing.JLabel jLabelStreet1;
    private javax.swing.JLabel jLabelStreet2;
    private javax.swing.JLabel jLabelTele;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldAffiliation;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldCareer;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldDegree1;
    private javax.swing.JTextField jTextFieldDegree1ED;
    private javax.swing.JTextField jTextFieldDegree1SD;
    private javax.swing.JTextField jTextFieldDegree2;
    private javax.swing.JTextField jTextFieldDegree2ED;
    private javax.swing.JTextField jTextFieldDegree2SD;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldMajor;
    private javax.swing.JTextField jTextFieldStreet1;
    private javax.swing.JTextField jTextFieldStreet2;
    private javax.swing.JTextField jTextFieldTele;
    // End of variables declaration//GEN-END:variables
}
